### ISSUE TITLE
Allow ordering iGNN sample sets according to population / sample set id

### ISSUE THREAD

**Issue by percyfal** [tforest/tseda#15]
Ordering refers both to the order of sample sets along the x axis as well as in what order bars are stacked.

**Comment by hannamlmv** [comment]
> There is a working implementation but would need to be simplified / improved. A Python list is currently supplied to the `Sort order` option of the `GNN VBar options` where the user indicates what population to sort (e.g., ['CEU']). Potential improvements:
> 
> * picking one population from a dropdown list
> * currently sorting is in ascending order, add option to choose descending / ascending

This is solved in my fork, however what do you mean by "Ordering refers both to the order of sample sets along the x axis as well as in what order bars are stacked.". Currently, the ordering only refers to the order bars are stacked in
