### ISSUE TITLE
Sample set table (and individuals table) should follow all panes

### ISSUE THREAD

**Issue by percyfal** [tforest/tseda#16]
Both sample set and individuals tables should be accessible in all panes since that is where custom sample sets are created, colors are changed, individuals selected for highlighting, and so on. Currently, the user has to switch back to the sample set editor and then back again. Preferably this could be achieved via a popup pane / box of some kind.

**Comment by percyfal** [comment]
This is currently done in the iGNN pane. Alternatively could live in separate browser window.

**Comment by hannamlmv** [comment]
alma is working on this

**Comment by almanilsson** [comment]
Solved in PR #85 on hannamlmv/tseda fork
