### ISSUE TITLE
Dropdown lists of color cells should show colors, not just hex strings

### ISSUE THREAD

**Issue by percyfal** [tforest/tseda#23]
`panel.Tabulator` tables can show cells as colors (see [Tabulator JS documentation](https://tabulator.info/docs/6.3/format#formatter-color)). By clicking on a cell, a dropdown list appears giving a choice of a number of predefined colors (currently a [categorical colormap called `glasbey.hv`](https://colorcet.holoviz.org/user_guide/Categorical.html#categorical). It would be nice if the dropdown cells show the actual colors instead of strings, but there does not seem to be any direct support for this as apparently the HTML `<select>` and `<option>` tags are browser specific (can't find the reference to this now though, could be that I'm wrong). CSS styling and / or JS-specific solution needed?

**Comment by hannamlmv** [comment]
Therese is working on this
