### ISSUE TITLE
Add slider to `trees` page to modify shown tree

### ISSUE THREAD

**Issue by percyfal** [tforest/tseda#25]
In addition to typing tree position or index, one could add a slider at the bottom of the trees plot. This can be achieved with the `param.Integer` parameter by setting the upper bound in `__init__`, and [enabling throttling](https://panel.holoviz.org/how_to/performance/throttling.html).

**Comment by hannamlmv** [comment]
working on this

**Comment by hannamlmv** [comment]
Addressed in [PR 87](https://github.com/hannamlmv/tseda/pull/87)
