### ISSUE TITLE
Refactor sample_sets() and get_sample_sets() functions

### ISSUE THREAD

**Issue by percyfal** [tforest/tseda#30]
The `IndividualsTable` methods `sample_sets()` and `get_sample_sets()` are confusingly named as they return similar objects. They need documentation and possibly merging to one function, `sample_sets()`, that returns a dictionary with a sample set id to samples list mapping.

**Comment by hannamlmv** [comment]
Solved in [PR 44](https://github.com/tforest/tseda/pull/44) on my fork
