### ISSUE TITLE
"Tracked samples" in trees

### ISSUE THREAD

**Issue by hyanwong** [tforest/tseda#31]
The tskit `trees()` iterator has the concept of "tracked samples": a single subset of samples for which it is quick to report the number of those samples under each node in the tree (see https://tskit.dev/tskit/docs/stable/python-api.html#tskit.Tree.num_tracked_samples). I could be neat to take advantage of this, e.g. I use it to define a focal set of samples when collapsing polytomies as below:

<img width="815" alt="Screenshot 2024-11-13 at 15 58 12" src="https://github.com/user-attachments/assets/d2aebd44-3d33-4a7c-8e17-74ea0fb65d2e">

(see https://tskit.dev/news/20241106-tskit-0.6.0.html#experimental-drawing-options)

It could be useful to be able to select one of the tsEDA-defined sample sets to act as the tracked samples, somehow.

**Comment by hyanwong** [comment]
Perhaps the easiest here is simply to be able to select a single sample set in the tree view, and say to focus on that. I think I can see how we might do that, and Gregor has some nice example datasets to test out for viz.

**Comment by hyanwong** [comment]
Note that there is a fix in GH for the (undocumented) `pack_untracked_polytomies` parameter to `draw_svg()`, so we should install the `main` branch from GitHub (`pip install git+https://github.com/tskit-dev/tskit#subdirectory=python`) before testing this.

**Comment by hannamlmv** [comment]
The tracked_samples parameter only seems to be applicable to a TreeSequence iterator, not to a single tree (https://tskit.dev/tskit/docs/stable/python-api.html#obtaining-trees). It looks to me as if the trees page does not use a TreeSequence iterator, as it accesses trees directly by index or position, and hence I can't really figure out how to add tracked samples to the displayed trees. 

Also, when I try to use the pack_untracked_polytomies option (as shown below) I get an error (ValueError: max() iterable argument is empty), maybe I am using it incorrectly I'm not really sure, as there is no documentation.

`        plot = tree.draw_svg(
        size=(self.width, self.height),
        symbol_size=self.symbol_size,
        y_axis=self.y_axis.value,
        x_axis=self.x_axis.value,
        omit_sites=omit_sites,
        node_labels=node_labels,
        y_ticks=y_ticks,
        pack_untracked_polytomies = True,
        style=self.default_css,
        **additional_options,
    )`

**Comment by hyanwong** [comment]
I think you should be able to pass the tracked samples to `ts.at()`, as **kwargs

```python
import msprime
ts = msprime.simulate(10)
ts.at(0.5, tracked_samples=[1,2,3])
```

**Comment by hyanwong** [comment]
> Also, when I try to use the pack_untracked_polytomies option I get an error (ValueError: max() iterable argument is empty)

Can you give me a reproducible example. E.g. the following works for me:

```python
import msprime
ts = msprime.simulate(10, random_seed=1)
tree = ts.at(0.5, tracked_samples=[1,2])
tree.draw_svg(
    size=(300, 300), symbol_size=4, y_axis=True, x_axis=True, omit_sites=False, pack_untracked_polytomies = True)
```

**Comment by hannamlmv** [comment]
Thanks, now it works! possibly, the problem with pack_untracked_polytomies was due to the fact that I hadn't defined any tracked samples

**Comment by hyanwong** [comment]
Ah yes, that could be the case. We should probably raise a helpful error in this case.
